### ISSUE TITLE
增加账号允许登录时间段设置

### ISSUE THREAD

**Issue by tkkcc** [AegirTech/Inquisition#2]
希望能设置每个账号的允许执行时间，面向两类需求：
1. 设置单个开始时间 => 玩家需要上号一段时间，要求今晚6点后才允许登录。
2. 设置星期几到星期几为允许时间 => 玩家双休日要上号，要求工作日才允许登录。

进阶需求：
1. 设置以分钟为单位的多个禁止时间段，几点几分到几点几分，由后端自动调度使其只在允许范围内登录，且满足一天三清。

可能太难了，我没整，但前两个应该能整

**Comment by DazeCake** [comment]
将会优先考虑前两条需求实现

**Comment by DazeCake** [comment]
所有需求已于 [1f838c0](https://github.com/AegirTech/Inquisition/commit/1f838c0c9fa9ef35f551304ea837cf6a2e6f3869) [43128d3](https://github.com/AegirTech/Inquisition/commit/43128d3e99e5efe693185869800263fca3428bb5) 分别实现
