### ISSUE TITLE
关于README里的一些错误

### ISSUE THREAD

**Issue by Mulsd** [AegirTech/Inquisition#6]
在 数据库配置 中
```
SOURCE https://fastly.jsdelivr.net/gh/AegirTech/Inquisition/main/sql/arklights.sql
```
应为
```
SOURCE https://fastly.jsdelivr.net/gh/AegirTech/Inquisition@main/sql/arklights.sql
```
——
在 配置文件 中配置的数据库（arklights）与上文 数据库配置中创建的数据库（inquisition）不一致
——
在 API文档 中
```
部署后[访问](http://127.0.0.1:2000/swagger-ui/index.htm)
```
应为
```
部署后[访问](http://127.0.0.1:2000/swagger-ui/index.html)
```
---
虽然对readme纠错没什么用（一般不会被这些问题折腾到），但是既然写了那就尽量把它修正确吧

**Comment by DazeCake** [comment]
感谢指正，确实是写的有些仓促。
关于 
>  `SOURCE https://fastly.jsdelivr.net/gh/AegirTech/Inquisition@main/sql/arklights.sql`

您有尝试过网络sql载入吗，我感觉可以，就没有尝试直接写了

**Comment by Mulsd** [comment]
> 感谢指正，确实是写的有些仓促。 关于
> 
> > `SOURCE https://fastly.jsdelivr.net/gh/AegirTech/Inquisition@main/sql/arklights.sql`
> 
> 您有尝试过网络sql载入吗，我感觉可以，就没有尝试直接写了

我也是看着它和jsdelivr正常连接格式不一样改的。
刚刚试了一下 ，不行

**Comment by DazeCake** [comment]
OK，已经修改为更合理的格式
