### ISSUE TITLE
关于证书的一些问题

### ISSUE THREAD

**Issue by czxxxcyz** [AegirTech/Inquisition#7]
给后端的证书应该不同于普通的网站证书吧，该如何申请还是自签证书，而且key-store-type意义也不明确。
貌似不加证书登录时就会“网络配置错误”

**Comment by DazeCake** [comment]
就是ssl证书，不加证书无法使用https会被浏览器策略拦截，所以需要添加证书。
key-store-type指证书类型，springboot支持证书类型有限，需要相关约束。

**Comment by czxxxcyz** [comment]
那普通的pem证书是可以的喽

**Comment by czxxxcyz** [comment]
不会还需要一个域名吧
